name: anonkey_frontend
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cryptography: ^2.7.0
  encrypt: ^5.0.3
  favicon: ^1.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  form_validator: ^2.1.1
  http: ^1.2.2
  openapi_generator: ^5.0.2
  openapi_generator_annotations: ^6.0.0
  shared_preferences: ^2.3.2
  rxdart: any
  intl: any
  flutter_iconpicker: ^4.0.0
  flutter_secure_storage: ^9.2.2
  go_router: ^14.2.8
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ansi_styles: any

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    # - .env
    # - .env.development
