name: Format Code on PR

on:
  pull_request

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Dart
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      # Step 3: Run dart format
      - name: Format Dart code
        run: dart format lib

      # Step 4: Commit and push changes
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Applied Formatting"
          add: 'lib'
          default_author: github_actions
          push: true